### ISSUE TITLE
Structor does not generates the full site

### ISSUE THREAD

**Issue by Xumeiquer** [containous/structor#17]
I am trying to build a documentation for a project and `structor` does not generates the main site, it actually builds the version branches and the experimental one, but not the main site.

Is it possible because the master branch has no mkdocs project on it?

I am running `structor` as following:
```
structor -o orga -r prj --dockerfile-url="https://raw.githubusercontent.com/orga/prj/dev/docs/docs.Dockerfile" --menu.js-url="https://raw.githubusercontent.com/orga/prj/dev/docs/prj-menu.js.gotmpl" --exclude="$OLD_BRANCHES" --force-edit-url --exp-branch=dev --debug;
```
I tried to mimic Traefik's doc automation, but I don't know if there is something missing?

**Comment by ldez** [comment]
Hello,

Structor generate that:

```
. (latest, branch v1.2)
├── ...
├── index.html
├── v1.0 (branch v1.0)
│   ├── ...
│   └── index.html
├── v1.1 (branch v1.1)
│   ├── ...
│   └── index.html
└── v1.2 (branch v1.2)
    ├── ...
    └── index.html
```

the `latest` (I guess it's what you call "main site") is obtain by using GitHub API or by using the env var `STRUCTOR_LATEST_TAG`

Check your logs to get more information.

**Comment by Xumeiquer** [comment]
The `STRUCTOR_LATEST_TAG ` solved the issue. Thanks.
