### ISSUE TITLE
Can Structor build documentation only for master branch?

### ISSUE THREAD

**Issue by Xumeiquer** [containous/structor#21]
Hi,
My project is in an early stage in which we do not have any branch release yet. Thus, can structor build the documentation when the only active branch is master and it is defined as experimental?

Thanks.

**Comment by ldez** [comment]
Hi, yes structor can build the documentation of the master when it's the only master branch.

**Comment by Xumeiquer** [comment]
Hello,

I am trying to build the documentation for the master branch and structor fails. I don't have any other branches at the moment as the project is in early stages. 

Please check this [line](https://www.travis-ci.org/github/mole-ids/mole/builds/690177099#L1426), which says `Error: error when build versions: Malformed version`. I did not set the `STRUCTOR_LATEST_TAG` as there are no tags (v* branches) to to build.

Any ideas how should I setup the structor to work properly?

Thanks.
