### ISSUE TITLE
Use the exp-branch as latest release

### ISSUE THREAD

**Issue by farodin91** [containous/structor#6]
I'm trying to use this project for JanusGraph. 

Our master branch could be the latest release:
- If we have a separated branch for our latest release, than master is our experimental branch.
For example: latest release is 0.3.1 and our master is already on the snapshot of 0.4. Here is the branch 0.3 the latest release and master the experimental branch.
- If we have a no separated branch for our latest release, than master is our latest release branch.
For example: latest release is 0.4.0 and our master is contains all changes which will go into to a upcoming release of 0.4. Here is the master branch is our latest release branch.

Reason: We create a new release branch at a point where breaking changes are added.

_Ps: Cool project!_

**Comment by ldez** [comment]
Hello, I understand your use case, I need to think about it.

**Comment by ldez** [comment]
I added the [sprig](http://masterminds.github.io/sprig/)  in version [v1.5.0](https://github.com/containous/structor/releases/tag/v1.5.0).

You can now easily change the JS menu file.

**Comment by farodin91** [comment]
Thank you, I will try to include this Monday.

**Comment by farodin91** [comment]
It works perfect.
