### ISSUE TITLE
Calculate the latest version using semver highest version number

### ISSUE THREAD

**Issue by farodin91** [containous/structor#7]
If we release a patch for a older version after a release of a current version, the patch of older version will be the latest version.
_I just look into the code, so this could be wrong._

**Comment by ldez** [comment]
I have to validate your assumption (I don't remember how the `/latest` works on Github), however you can use `STRUCTOR_LATEST_TAG` (in your CI) to fix the latest.

**Comment by farodin91** [comment]
Thanks. I didn't saw this in the readme.md
